### PR TITLE
Fix notebook timeout and batch python files execution

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/47)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by mreid-moz** [comment]
Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[jobs/telemetry_aggregator.py, line 10 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/47#-KSppKWXbRfGsAie7LQp:-KSppKWYFSoTnEpb_csZ:bfy5yvp) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/84dbad37d9c5c191fb70cf564d61f892817b4eaa/jobs/telemetry_aggregator.py#L10)):*
> ```Python
> 
> conf = SparkConf().setAppName('telemetry-aggregates')
> sc = SparkContext(conf=conf)
> ```

Do you need to "stop" the SparkContext like we needed to do over in Scala-land?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/47)*

**Comment by maurodoglio** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[jobs/telemetry_aggregator.py, line 10 at r3](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/47#-KSppKWXbRfGsAie7LQp:-KSpupL3-XM7YO96YbYG:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/84dbad37d9c5c191fb70cf564d61f892817b4eaa/jobs/telemetry_aggregator.py#L10)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Do you need to "stop" the SparkContext like we needed to do over in Scala-land?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/47)*

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/47#-:-KSpvFOkJPYmWY-bDkNy:bnfp4nl)*

**Pull request merged**
