### PR TITLE
Bug 1314120 - Add socorro_import dag

### PR DESCRIPTION
**Pull request by acmiyaguchi**
The ImportCrashData notebook in mozilla/data-pipeline should now be able to run in a production setting. This schedules the crash data import job on a daily basis.

@mreid-moz r?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/70)

### CODE REVIEW

**Comment by mreid-moz** [comment]
@maurodoglio if you have time tomorrow, please r?  Otherwise I will take a look on Monday.

**Comment by mreid-moz** [comment]
@maurodoglio I'm on it now.

**Comment by maurodoglio** [comment]
Sorry, I missed the notification from github :(

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[dags/socorro_import.py, line 20 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXxFRDos0v7mgjoyQ9:-KWXxFRDos0v7mgjoyQA:bq0o5wr) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L20)):*
> ```Python
> t0 = EMRSparkOperator(task_id="socorro_import",
>                       job_name="Import crash data",
>                       execution_timeout=timedelta(hours=4),
> ```

IIRC, you've been testing on Spark 2. If so, please add a `release_label="emr-5.0.0"` arg.

---

*[dags/socorro_import.py, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXx5qGD1OJS8amo01Z:-KWXx5qHheW5U8lzLqt8:bk8xowz) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L22)):*
> ```Python
>                       execution_timeout=timedelta(hours=4),
>                       instance_count=5,
>                       owner="amiyaguchi@mozilla.com",
> ```

You can remove the `owner` and `email` kwargs here, they are already specified above in the defaults.

---

*[dags/socorro_import.py, line 25 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXyRl0gvOu_dXiwMpr:-KWXyRl1F8dfzbokCWNL:bvqgan6) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L25)):*
> ```Python
>                       email=["telemetry-alerts@mozilla.com", "amiyaguchi@mozilla.com"],
>                       env={"date": "{{ ds_nodash }}"},
>                       uri="https://raw.githubusercontent.com/mozilla-services/data-pipeline/master/reports/socorro_import/ImportCrashData.ipynb",
> ```

This will require one more change to `ImportCrashData.ipynb`. It should look up the target date from the environment (checking the `date` arg passed above), and fall back to running for "yesterday" if no date is found. There is an example of this [here](https://github.com/mozilla/telemetry-airflow/blob/master/examples/spark/example_date.ipynb)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70)*

**Comment by acmiyaguchi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[dags/socorro_import.py, line 20 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXxFRDos0v7mgjoyQ9:-KWZrzZw-3VF-bZul5Um:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L20)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> IIRC, you've been testing on Spark 2. If so, please add a `release_label="emr-5.0.0"` arg.
</details>
Done.

---

*[dags/socorro_import.py, line 22 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXx5qGD1OJS8amo01Z:-KWZs-QOO9U0I-dUfbuH:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L22)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> You can remove the `owner` and `email` kwargs here, they are already specified above in the defaults.
</details>
Done.

---

*[dags/socorro_import.py, line 25 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXyRl0gvOu_dXiwMpr:-KWZs03RkuTFJKxd6jiX:bov3p06) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L25)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> This will require one more change to `ImportCrashData.ipynb`. It should look up the target date from the environment (checking the `date` arg passed above), and fall back to running for "yesterday" if no date is found. There is an example of this [here](https://github.com/mozilla/telemetry-airflow/blob/master/examples/spark/example_date.ipynb)
</details>
Will this date argument that is passed to the notebook be for the previous day e.g. when a job is scheduled on 11/14, will the date argument read '20161113'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70)*

**Comment by acmiyaguchi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[dags/socorro_import.py, line 24 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWZwRnfVgFg-fCWjT96:-KWZwRnfVgFg-fCWjT97:b-562d3j) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L24)):*
> ```Python
>                       owner="amiyaguchi@mozilla.com",
>                       email=["telemetry-alerts@mozilla.com", "amiyaguchi@mozilla.com"],
>                       env={"date": "{{ ds_nodash }}"},
> ```

Do we want this to be `yesterday_ds_nodash`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70)*

**Comment by mreid-moz** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[dags/socorro_import.py, line 24 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWZwRnfVgFg-fCWjT96:-KW_TERXy3tXp6c0W3Vb:b-8dqm0k) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L24)):*
<details><summary><i>Previously, acmiyaguchi (Anthony Miyaguchi) wrote…</i></summary>
> Do we want this to be `yesterday_ds_nodash`?
</details>
The other daily jobs all use `ds_nodash`, so we should be OK. The job runs at the end of the given day.

---

*[dags/socorro_import.py, line 25 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70#-KWXyRl0gvOu_dXiwMpr:-KW_U11sN2FY17bZ4MFu:b-batrtm) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/d45801c722c86eac122bcf14cd03f64f24bfafb2/dags/socorro_import.py#L25)):*
<details><summary><i>Previously, acmiyaguchi (Anthony Miyaguchi) wrote…</i></summary>
> Will this date argument that is passed to the notebook be for the previous day e.g. when a job is scheduled on 11/14, will the date argument read '20161113'?
</details>
Jobs run at midnight at the end of the current day, so the target date is over by the time the job runs. If more time is needed for data to roll in, we can build in a delay similar to the main_summary job.

I had a quick look at the timestamps on the source objects on S3 and they appear to almost all arrive during the day or within a few seconds after UTC midnight. The time taken to spin up a cluster should more than cover the normal case. There are a few stragglers (< 0.01%) that seem to be able to arrive later (even a full day later in one case I saw), so we should file a follow-up bug for how best to handle those ones.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/70)*

**Comment by mreid-moz** [comment]
This has been deployed.

**Pull request merged**
