### PR TITLE
Bug 1275889 - Prepare "Main Summary" job for backfill

### PR DESCRIPTION
**Pull request by mreid-moz**
Set the max number of active runs so we don't overwhelm the system,
and rewind the start date by a couple of days to test that the
scheduler does the right thing.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/30)

### CODE REVIEW

**Comment by mreid-moz** [comment]
r? @vitillo 

Note that this is part 1 of 2. Assuming it works according to plan, the next part is to update the "start date" back to the beginning of the backfill period.

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/main_summary.py, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30#-KNgl3YhuoufpfELjl4q:-KNgl3YhuoufpfELjl4r:-221821190) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/90bee3a1b3b4a9feef5843538d91ee37a56d2aab/dags/main_summary.py#L17)):*
> ```Python
> }
> 
> dag = DAG('main_summary', default_args=default_args, schedule_interval='@daily', max_active_runs=10)
> ```

How does this interact with our current [settings](https://github.com/mozilla/telemetry-airflow/blob/master/ansible/files/airflow/airflow.cfg#L33)? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/main_summary.py, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30#-KNgl3YhuoufpfELjl4q:-KNh0W4lkPuwt3ui-6bh:1267776644) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/90bee3a1b3b4a9feef5843538d91ee37a56d2aab/dags/main_summary.py#L17)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> How does this interact with our current [settings](https://github.com/mozilla/telemetry-airflow/blob/master/ansible/files/airflow/airflow.cfg#L33)? 
</details>
Good question. I think this should be set to a value lower than `parallelism`, `dag_concurrency` and `max_active_runs_per_dag`. I thought I could rely on max_active_runs_per_dag when doing backfill, but Airflow happily allowed me to run 6 tasks at once (when manually doing Main Summary backfill). Maybe that's because it was just running task instances and not full dags.

In any case, I suggest the following additional changes:
```
parallelism = 16
dag_concurrency = 16
max_active_runs_per_dag = 10
```

What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/main_summary.py, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30#-KNgl3YhuoufpfELjl4q:-KNlNuTuCCwt6cpL_NEu:-682275779) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/90bee3a1b3b4a9feef5843538d91ee37a56d2aab/dags/main_summary.py#L17)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Good question. I think this should be set to a value lower than `parallelism`, `dag_concurrency` and `max_active_runs_per_dag`. I thought I could rely on max_active_runs_per_dag when doing backfill, but Airflow happily allowed me to run 6 tasks at once (when manually doing Main Summary backfill). Maybe that's because it was just running task instances and not full dags.
> 
> In any case, I suggest the following additional changes:
> ```
> parallelism = 16
> dag_concurrency = 16
> max_active_runs_per_dag = 10
> ```
> 
> What do you think?
> 
</details>
Sounds good to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30)*

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/30#-:-KOAWSo9xn3DpxuSvm6a:1417088721)*

**Pull request merged**
