### PR TITLE
Bug 1338615 - daily search rollup notebook

### PR DESCRIPTION
**Pull request by SamPenrose**
Downstream from main_summary. Points at a gist -- is that OK?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/84)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by sunahsuh** [comment]
Hey Sam, taking a look at this since mreid is on PTO until next week --
there's no technical reason you can't use a gist, but given you're adding a daily 30-node job it seems like a good idea to get a good review on the job code and put it somewhere that's more accessible for everyone. A lot of our other airflow python jobs are located here: https://github.com/mozilla-services/data-pipeline/tree/master/reports

**Comment by vitillo** [comment]
I agree with @sunahsuh with one comment: new notebooks should be pushed to [RTMO](https://github.com/mozilla/mozilla-reports) and not to the data-pipeline repo.

**Comment by SamPenrose** [comment]
This notebook is not a report, it is an ETL script. I can leave it as a gist or stick it on GH as a .py file. Preference?

**Comment by vitillo** [comment]
That's fine, we have other ETL scripts in mozilla-reports as well; as they get indexed it's easier for others to find examples.

**Comment by SamPenrose** [comment]
This PR depends on https://github.com/mozilla/mozilla-reports/pull/23 and will need to be updated; please don't merge it yet.

**Comment by SamPenrose** [comment]
Using a Gist for now per https://github.com/mozilla/mozilla-reports/pull/23

**Pull request merged**
