### PR TITLE
Bug 1519999 - Bump default release label for MozDatabricksSubmitRunOp…

### PR DESCRIPTION
**Pull request by acmiyaguchi**
…erator

https://docs.databricks.com/release-notes/runtime/5.1.html

### CODE REVIEW

**Comment by acmiyaguchi** [comment]
Based on issues in https://github.com/mozilla/telemetry-batch-view/pull/518 and @akkomar, there may be incompatibilities between the bundled json4s version and the version on Databricks.

We should wait until we run some preliminary testing to merge this in.

**Comment by sunahsuh** [comment]
I'm going to reassign the review to @akkomar then since he'll have more context :)

**Comment by akkomar** [comment]
@acmiyaguchi here's the error thrown after running above-mentioned job on runtime v5.1:
`Exception in thread "main" java.lang.NoSuchMethodError: org.json4s.jackson.JsonMethods$.parse(Lorg/json4s/JsonInput;Z)Lorg/json4s/JsonAST$JValue;`, source: https://dbc-caf9527b-e073.cloud.databricks.com/#setting/sparkui/0122-195330-manse145/driver-logs

**Comment by acmiyaguchi** [comment]
I added a testing DAG that can be triggered externally. Modify the `Dockerfile.dev` to include the appropriate AWS keys, then run the following script:

```bash
#!/bin/bash

HOST='https://dbc-caf9527b-e073.cloud.databricks.com'
EXTRA='{"token":"<TOKEN>"}'

docker-compose exec web \
    airflow connections \
        --delete \
        --conn_id databricks_default

docker-compose exec web \
    airflow connections \
        --add \
        --conn_id databricks_default \
        --conn_type databricks \
        --conn_host ${HOST} \
        --conn_extra ${EXTRA}

docker-compose exec web \
    airflow trigger_dag platform_compat
```

I've verified that the exception exists on runtime 5.1 with this.

**Pull request closed without merging**
