### PR TITLE
Bug 1286201 - add dag for bugzilla dataset update

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/31)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 14 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm66bpwTdTuvocMxG3:-KNm66bqTOidGueUhAZo:1986765217) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/.travis.yml#L14)):*
> ```YAML
>   - airflow initdb
> script:
>   - airflow list_dags
> ```

Nice! 

---

*[dags/bugzilla_dataset.py, line 19 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm6HevHTvxDjUkVuDg:-KNm6HevHTvxDjUkVuDh:-1755169290) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/dags/bugzilla_dataset.py#L19)):*
> ```Python
> dag = DAG('bugzilla_dataset', default_args=default_args, schedule_interval='@daily')
> 
> connection_details = BaseHook.get_connection('bugzilla_db')
> ```

How have you tested this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31)*

**Comment by maurodoglio** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 14 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm66bpwTdTuvocMxG3:-KNqHQ3ZSG9gFjEomsrK:1479498506) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/.travis.yml#L14)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Nice! 
</details>
Yeah but it's still failing

---

*[dags/bugzilla_dataset.py, line 19 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm6HevHTvxDjUkVuDg:-KNqCQuHnIF-HhWjFUeU:1077406679) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/dags/bugzilla_dataset.py#L19)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> How have you tested this?
</details>
I haven't, that's why I wanted to at least have some validation using list_dags. The command to test tasks reported in the README doesn't seem to work for me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31)*

**Comment by vitillo** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[dags/bugzilla_dataset.py, line 19 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm6HevHTvxDjUkVuDg:-KNqx9lkBe1wVDQ9Gq_H:1276874756) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/dags/bugzilla_dataset.py#L19)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> I haven't, that's why I wanted to at least have some validation using list_dags. The command to test tasks reported in the README doesn't seem to work for me.
</details>
Could you please file a bug and possibly try to debug why it doesn't work for you?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31)*

**Comment by vitillo** [comment]
@maurodoglio might be worthwhile to either fix the travis build or remove it from this commit.

**Comment by maurodoglio** [comment]
Yeah I'll disable travis builds for now.

**Comment by maurodoglio** [comment]
It's disabled now.

---

Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[dags/bugzilla_dataset.py, line 19 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm6HevHTvxDjUkVuDg:-KPSeNv7470PFNCmyplO:b-x6asxq) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/dags/bugzilla_dataset.py#L19)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Could you please file a bug and possibly try to debug why it doesn't work for you?
</details>
It wasn't working because the connection object was not there. I tested it using the default postgresql connection and it worked

---

*[.travis.yml, line 14 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-KNm66bpwTdTuvocMxG3:-KPSelk3IR06GCs2ZSqM:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/0f58804fa157aa01093993e3e9e7924a6ddfcb86/.travis.yml#L14)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> Yeah but it's still failing
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31#-:-KPSee2I0hLSLgTmKFde:bwncva0)*

**Comment by vitillo** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/31)*

**Pull request merged**
