### PR TITLE
Add update orphaning job to Airflow

### PR DESCRIPTION
**Pull request by sapohl**
This depends on the longitudinal job running successfully to run.

needs-review: @vitillo

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/21)

### CODE REVIEW

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/longitudinal.py, line 26 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21#-KMPJGTM_KVqfZW-bxNi:-KMPJGTN7Q90hqpFal4Z:-481554576) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/e32c67197490f7dd5e6c0110d4a1b937ee1ab8c9/dags/longitudinal.py#L26)):*
> ```Python
>                       dag=dag0)
> 
> update_orphaning_args = {
> ```

You shouldn't create a new DAG, just a new task and add that task to the existing DAG. Please have a look at the [documentation](https://pythonhosted.org/airflow/tutorial.html) on how to do that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21)*

**Comment by sapohl** [comment]
Addressed review feedback

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21#-KMTptC6EhY27WRcPRXy:-KMTptC6EhY27WRcPRXz:114653617) (no related file):*
Please rebase your latest commit onto the first one as they both belong logically together.

---

*[dags/longitudinal.py, line 33 \[r2\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21#-KMTnK8jBtQFd5M41Dw1:-KMTnK8jBtQFd5M41Dw2:467101095) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/3844ae6d79e58d99c8a66c4ef1f41e7663a21d03/dags/longitudinal.py#L33)):*
> ```Python
>                       email=["telemetry-alerts@mozilla.com", "spohl@mozilla.com",
>                              "mhowell@mozilla.com"],
>                       env={"date": "{{ ds_nodash }}", "bucket": "{{ task.__class__.airflow_bucket }}"},
> ```

Note that the notebook should take into account the `date` variable passed through the environment (and not use `date.today`). Your job is also not using the `bucket` parameter so there is no reason why you should pass it. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21)*

**Comment by sapohl** [comment]
Rebased and addressed feedback. I will update the job to use the `date` variable next.

**Comment by vitillo** [comment]
LGTM

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/21#-:-KMZnVc2o6d1xU0AdBqS:676834233)*

**Comment by vitillo** [comment]
Let's redeploy once your changes to the notebook have landed.

**Pull request merged**
