### PR TITLE
decommission desktop_active_dau

### PR DESCRIPTION
**Pull request by relud**
this is actively used by one query https://sql.telemetry.mozilla.org/queries/52720/source which needs to be updated to pick up the changes at https://github.com/mozilla/stmo_core_product_metrics/pull/21

### CODE REVIEW

**Comment by akkomar** [comment]
> this is actively used by one query https://sql.telemetry.mozilla.org/queries/52045/source#138916 

You mean this one: https://sql.telemetry.mozilla.org/queries/52720/source ? @mreid-moz - do you need this query?

**Comment by relud** [comment]
oops, my bad. yes, that one.

**Comment by akkomar** [comment]
> > this is actively used by one query https://sql.telemetry.mozilla.org/queries/52045/source#138916
> 
> You mean this one: https://sql.telemetry.mozilla.org/queries/52720/source ? @mreid-moz - do you need this query?

This query is used in the [dashboard](https://sql.telemetry.mozilla.org/dashboard/mdc-required-container-dashboard-for-dau) linked from MDC. @mreid-moz emailed MDC team about this today.

**Comment by mreid-moz** [comment]
I think it should be safe to switch 52720 to use the more modern "exact mau" tables for this query, though I would prefer to drop it altogether if I can verify that they're no longer needed in MDC.

**Comment by mreid-moz** [comment]
I checked, and this query _is_ linked to from MDC, so we should update it to used the `exact_*` tables.

**Comment by relud** [comment]
I double-checked the results of the query before and after using exact active mau, and the graphs look almost identical, exact is just smoother, so i went ahead and updated the query. this PR should now be safe to merge.

**Pull request merged**
