### PR TITLE
Schedule training the Addon Recommender

### PR DESCRIPTION
**Pull request by Dexterp37**
r? @vitillo - Also, should you own this job or should I (or somebody else :-D)?

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/35)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
Whoever owns it is responsible to fix it when it breaks. I am OK with you owning it ;)

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dags/longitudinal.py, line 45 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHwkJ3xSfRNBkhyZgL:-KPHwkJ3xSfRNBkhyZgM:b-86hhuq) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/dags/longitudinal.py#L45)):*
> ```Python
>                       email=["telemetry-alerts@mozilla.com", "rvitillo@mozilla.com",
>                              "aplacitelli@mozilla.com"],
>                       env={"date": "{{ ds_nodash }}", "bucket": "{{ task.__class__.private_output_bucket }}"},
> ```

How is the `bucket` parameter used by the job? I thought we wanted to store the data in `telemetry-ml`.

---

*[jobs/addon_recommender.sh, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHy1AQflUW7XWBHOuz:-KPHy1AQflUW7XWBHOv-:b-12ya9z) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/jobs/addon_recommender.sh#L17)):*
> ```Shell
>              train \
>              --output ml_output
>              --bucket $bucket
> ```

What are those parameters used for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-:-KPHwJbaYl7qDVwBW0ML:b-epy2ik)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[jobs/addon_recommender.sh, line 17 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHy1AQflUW7XWBHOuz:-KPI-saCGMFdVViX6NZ3:b-dst0zc) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/jobs/addon_recommender.sh#L17)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What are those parameters used for?
</details>
Nevermind, I just saw the corresponding PR for `telemetry-batch-view`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35)*

**Comment by Dexterp37** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/longitudinal.py, line 45 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHwkJ3xSfRNBkhyZgL:-KPINiTvfN2z2kIhg7eE:bmo27mb) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/dags/longitudinal.py#L45)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> How is the `bucket` parameter used by the job? I thought we wanted to store the data in `telemetry-ml`.
</details>
The job itself stores the data in s3://$bucket/telemetry-ml/addon_recommender/$date/
Is that what you meant?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/longitudinal.py, line 45 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHwkJ3xSfRNBkhyZgL:-KPIXs9uHKd5mK-nAI6-:bqqpzmk) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/dags/longitudinal.py#L45)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> The job itself stores the data in s3://$bucket/telemetry-ml/addon_recommender/$date/
> Is that what you meant?
</details>
What I meant is that you should pass `telemetry-ml` as bucket. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35)*

**Comment by Dexterp37** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/longitudinal.py, line 45 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-KPHwkJ3xSfRNBkhyZgL:-KPIh964_nJm4S-dJkGG:bypppwe) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/48d1124d021fceaab4398fc79845263c81ead875/dags/longitudinal.py#L45)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> What I meant is that you should pass `telemetry-ml` as bucket. 
</details>
I've changed that as discussed over IRC: we're providing both the private and public buckets to the job, nothing will get saved to the telemetry-ml bucket.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35)*

**Comment by vitillo** [comment]
:lgtm: Let's land this once the corresponding patch in telemetry-batch-view lands.

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/35#-:-KPIjRiuaiI6qz5-Ryy_:b-gjknwj)*

**Pull request merged**
