### PR TITLE
Bug 1689167 - Up probe-scraper mem by 50%

### PR DESCRIPTION
**Pull request by fbertsch**

### CODE REVIEW

**Comment by fbertsch** [comment]
This is not the long-term fix. Clearly this job does not need to use all of this memory.

**Review by haroldwoo — APPROVED** [review]
If this doesnt schedule we need to create nodes with more memory

**Comment by haroldwoo** [comment]
Ok i checked and this will likely fail. The highmem pool is comprised of n1-highmem-4 instances, which have only 26GB of memory total. https://cloud.google.com/compute/docs/machine-types

**Comment by haroldwoo** [comment]
> This is not the long-term fix. Clearly this job does not need to use all of this memory.

I'm not sure what you mean by this. If the job doesn't require this memory then why are we doing this?

**Comment by fbertsch** [comment]
> > This is not the long-term fix. Clearly this job does not need to use all of this memory.
> 
> I'm not sure what you mean by this. If the job doesn't require this memory then why are we doing this?

What I mean is this is a temporary fix. We are doing it because this blocks schema deploys for the entire pipeline. We need to do a memory profile analysis and see what is causing this leakage.

**Pull request merged**
