### PR TITLE
Bug 1286825: Wrap the scheduler in a retry loop

### PR DESCRIPTION
**Pull request by mreid-moz**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/25)

### CODE REVIEW

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyUd-Pd8jxx05QYfA3:-448903425) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
> ```Shell
> sleep 5
> 
> case "$COMMAND" in
> ```

The command could be followed by arguments (for testing purposes) and the current approach would not work in that case.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by mreid-moz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyV-Td9rZTYf0v7T-M:1283701405) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> The command could be followed by arguments (for testing purposes) and the current approach would not work in that case.
</details>
It only changes the behaviour for the "scheduler" command.  If we are changing the arguments for the scheudler, it will need special handling in any case. It should not affect any of the other airflow subcommands.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyWJLakI8_fonQDavr:504602039) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> It only changes the behaviour for the "scheduler" command.  If we are changing the arguments for the scheudler, it will need special handling in any case. It should not affect any of the other airflow subcommands.
</details>
Why would it need special handling in any case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by mreid-moz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyfaAsA4hMSRkHDVty:1245829815) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Why would it need special handling in any case?
</details>
Because we need to make sure it includes the `num_runs` parameter so that it actually exits (allowing the retry loop to work).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyhce71TqFRnlzv_t_:-944873697) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Because we need to make sure it includes the `num_runs` parameter so that it actually exits (allowing the retry loop to work).
</details>
It should be possible to run any command (scheduler or not) with arbitrary parameters directly from the ansible script. This is needed for testing purposes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by mreid-moz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyiN95avYN7dXCC0Zp:-44126684) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> It should be possible to run any command (scheduler or not) with arbitrary parameters directly from the ansible script. This is needed for testing purposes
</details>
Hm, I could change it to wrap a retry loop if the `$COMMAND` variable contains the string `scheduler` instead... would that work for you? Then the `-n 5` param would move out to the ansible script.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMyiyJfQpeGpY_SUwyZ:-1915328531) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, mreid-moz (Mark Reid) wrote…</i></summary>
> Hm, I could change it to wrap a retry loop if the `$COMMAND` variable contains the string `scheduler` instead... would that work for you? Then the `-n 5` param would move out to the ansible script.
</details>
Yeah, that makes sense, you could check if `$1 == scheduler`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by vitillo** [comment]
Reviewed 3 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by mreid-moz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[ansible/files/airflow/entrypoint.sh, line 47 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25#-KMyUd-OtEIgMEw1bNp-:-KMz6-OFvqmkeeM8PGsv:-496149620) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/f33609f9ca951d68ff89754350d9e9b79817af13/ansible/files/airflow/entrypoint.sh#L47)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Yeah, that makes sense, you could check if `$1 == scheduler`.
</details>
We now check if the command starts with `scheduler`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/25)*

**Comment by vitillo** [comment]
Redeployed.

**Pull request merged**
