### PR TITLE
[DSRE-22] Test Jira integration

### PR DESCRIPTION
**Pull request by haroldwoo**
[DSRE-22]

### CODE REVIEW

**Comment by data-sync-user** [comment]
DSRE-22

**Comment by haroldwoo** [comment]
test [DSRE-22]

**Comment by haroldwoo** [comment]
DSRE-22

**Comment by haroldwoo** [comment]
DSRE-22 test

**Comment by data-sync-user** [comment]
DSRE-22 testing jira comment

**Comment by data-sync-user** [comment]
[DSRE-22] testing jira comment

**Comment by data-sync-user** [comment]
DSRE-22 #comment connected Github for Jira app today.

**Pull request closed without merging**
