### PR TITLE
Schedule the game HW survey job

### PR DESCRIPTION
**Pull request by Dexterp37**
The scheduled notebook computes the data for the past week, and appends it to the current state.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/34)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/longitudinal.py, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYG1EZEaYWkcsl5et:-KPDYG1EZEaYWkcsl5eu:b4l7l5z) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L44)):*
> ```Python
>                       owner="aplacitelli@mozilla.com",
>                       email=["telemetry-alerts@mozilla.com", "aplacitelli@mozilla.com"],
>                       uri="https://github.com/mozilla/firefox-hardware-survey/raw/master/report/summarize_json.ipynb",
> ```

The url doesn't seem to point to anything. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[dags/longitudinal.py, line 39 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYT7um7vXNB_rOwtf:-KPDYT7vKAqxqyay8ITS:b6s7cou) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L39)):*
> ```Python
> 
> t2 = EMRSparkOperator(task_id="game_hw_survey",
>                       job_name="Game Hardware Survey",
> ```

You might want to use the `depends_on_past` option if your job has to be invoked sequentially.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by Dexterp37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[dags/longitudinal.py, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYG1EZEaYWkcsl5et:-KPDZBzoTYVb5opnxm-m:bkeh0m4) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L44)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> The url doesn't seem to point to anything. 
</details>
Mh, good point. It looks like the repository is private. I guess this can't be scheduled until the repo is made public, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by vitillo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[dags/longitudinal.py, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYG1EZEaYWkcsl5et:-KPDdK4Os_o4tt0QoD2j:b-81la7d) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L44)):*
<details><summary><i>Previously, Dexterp37 (Alessio Placitelli) wrote…</i></summary>
> Mh, good point. It looks like the repository is private. I guess this can't be scheduled until the repo is made public, right?
</details>
Right

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by Dexterp37** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[dags/longitudinal.py, line 39 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYT7um7vXNB_rOwtf:-KPMKlZn2smzNRvqyqts:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L39)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> You might want to use the `depends_on_past` option if your job has to be invoked sequentially.
</details>
Done.

---

*[dags/longitudinal.py, line 44 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-KPDYG1EZEaYWkcsl5et:-KPMKqx9nsHTCDKvjlHm:b8tlyw9) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/cd27b2f34c5ab01ee765197143291075f54b9aef/dags/longitudinal.py#L44)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> Right
</details>
Ok, the repository is now public and you should be able to see the link!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Comment by vitillo** [comment]
@Dexterp37 Please rebase on master.

**Comment by Dexterp37** [comment]
Done

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34#-:-KPMutqktCTP7XupuvQE:bb6un1j)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/34)*

**Pull request merged**
