### PR TITLE
fix: bug-1579266 update socorro import to pull from gcs

### PR DESCRIPTION
**Pull request by relud**
## Description

update `socorro_import` to pull from gcs now that socorro has been migrated to GCP. I have temporarily paused the dag until this is resolved.

## Related Tickets & Documents
* bug 1579266
* https://github.com/mozilla-it/webservices-infra/pull/2188

### CODE REVIEW

**Review by ANich — APPROVED** [review]
LGTM if upstream is writing directly to gcs instead of s3

**Comment by relud** [comment]
@ANich i'll need you to merge this, i lack the permissions

**Pull request merged**
