### PR TITLE
Bug 1286242 - add mobile_clients dag

### PR DESCRIPTION
**Pull request by maurodoglio**
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/32)

### CODE REVIEW

**Comment by vitillo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-:-KOzTjBjBP1PxjcXo2Gw:bnfp4nl)*

**Comment by vitillo** [comment]
We should disable the travis build for this repo.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-:-KOzTpMEyCask4OhHaW6:b-hnt85d)*

**Comment by vitillo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[dags/mobile_clients.py, line 25 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-KOzTz00VqK52HcQWFa0:-KOzTz00VqK52HcQWFa1:brpc51i) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/39628236c033f696ca7f63b465ee659a9820aa34/dags/mobile_clients.py#L25)):*
> ```Python
>                       email=["telemetry-alerts@mozilla.com", "mdoglio@mozilla.com"],
>                       env={"date": "{{ ds_nodash }}"},
>                       uri="https://raw.githubusercontent.com/maurodoglio/user-data-analytics/master/mobile-clients.ipynb",
> ```

This should be move under `mozilla-services/data-pipeline/master/reports`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32)*

**Comment by maurodoglio** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/mobile_clients.py, line 25 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-KOzTz00VqK52HcQWFa0:-KOzfBTAOCYts-_R0KsH:b-utls57) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/39628236c033f696ca7f63b465ee659a9820aa34/dags/mobile_clients.py#L25)):*
<details><summary><i>Previously, vitillo (Roberto Agostino Vitillo) wrote…</i></summary>
> This should be move under `mozilla-services/data-pipeline/master/reports`
</details>
Opened https://github.com/mozilla-services/data-pipeline/pull/223 and changed the reference in the dag definition.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32)*

**Comment by maurodoglio** [comment]
done

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-:-KOzfVFAlvTOB7CHrGcL:bb7f2mf)*

**Comment by maurodoglio** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[dags/mobile_clients.py, line 25 \[r1\]](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32#-KOzTz00VqK52HcQWFa0:-KOzfZ9DV_e12S3pc3TI:b-896fix) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/39628236c033f696ca7f63b465ee659a9820aa34/dags/mobile_clients.py#L25)):*
<details><summary><i>Previously, maurodoglio (Mauro Doglio) wrote…</i></summary>
> Opened https://github.com/mozilla-services/data-pipeline/pull/223 and changed the reference in the dag definition.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/32)*

**Pull request merged**
