### PR TITLE
Bug 1301680 - Remove backfill DAG

### PR DESCRIPTION
**Pull request by mreid-moz**
Backfill has completed, we don't need this dummy DAG anymore.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/40)

### CODE REVIEW

**Comment by mreid-moz** [comment]
@vitillo is there anything else we need to do to remove a DAG? This is the first time I've tried it.  According to [this](https://groups.google.com/d/msg/airbnb_airflow/GVsNsUxPRC0/-oPIS1UuCAAJ) we may need to modify the db to remove references to the deleted DAG.

**Comment by vitillo** [comment]
I am not sure if any other action is required, have you tried removing a DAG locally by chance to see if the scheduler just dies?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/40#-:-KRdbhFn17gqDSZvGa4j:bp1tfu5)*

**Comment by vitillo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/40)*

**Comment by mreid-moz** [comment]
The local deployment wipes out the database every time, so it doesn't "remember" the existence of old DAGs locally.

I'm not sure how to test it in a similar way to the AWS deployment.

**Comment by vitillo** [comment]
You can test it by manually deleting the DAG from the local deployment.

**Comment by mreid-moz** [comment]
Ok, I've removed the file locally, and it still shows in the UI (but does not appear to cause any errors).  If I run the cleanup queries linked in my comment from a few days ago, the DAG disappears from the UI.

**Comment by vitillo** [comment]
Looks good, thanks!

**Pull request merged**
