### PR TITLE
[Bug 1830729] Specify project for view deploys

### PR DESCRIPTION
**Pull request by scholtzan**
To fix view deploys

### CODE REVIEW

**Review by whd — APPROVED** [review]
I take it this isn't completely redundant with `--target-project` for some reason related to a lack of fully qualified references, though the upstream bug doesn't say anything about this. Ideally we'd fully qualify everything and run airflow jobs from the main projects.

**Comment by scholtzan** [comment]
`--project_id` specifies which project directory views should be published from. (default is shared-prod) `--target_project_id` specifies the GCP project these views should be published in.

**Comment by whd** [comment]
> `--project_id` specifies which project directory views should be published from. (default is shared-prod) `--target_project_id` specifies the GCP project these views should be published in.

I take it the only time these would differ is `mozdata` due to its special handling?

**Comment by scholtzan** [comment]
yep

**Pull request merged**
