### PR TITLE
Add ETL job for the HBase main_summary view

### PR DESCRIPTION
**Pull request by vitillo**
Please merge only after the relative PR in telemetry-batch-view has been merged.

---
This change is [Reviewable](https://reviewable.io/reviews/mozilla/telemetry-airflow/78)

### CODE REVIEW

**Comment by autolander** [comment]
Autolander could not find a bug number in your pull request title. All pull requests should be in the format of: Bug [number] - [description].

**Comment by vitillo** [comment]
@mreid-moz r?

**Comment by mreid-moz** [comment]
LGTM

One minor suggestion, though it doesn't need to block this landing.

Feel free to merge whenever it's ready.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[jobs/hbase_main_summary_view.sh, line 12 at r1](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/78#-KZgJqHwS8dfe0Y-4pk8:-KZgJqHxg51b5yJpVTTT:b-yktjx3) ([raw file](https://github.com/mozilla/telemetry-airflow/blob/314c64fb74a14a01592c3f4326df611014113831/jobs/hbase_main_summary_view.sh#L12)):*
> ```Shell
> sbt assembly
> 
> hbase=$(aws ec2 describe-addresses --filters Name=public-ip,Values=52.24.192.75 | jq -r '.Addresses[0].PrivateIpAddress')
> ```

I don't particularly like referencing the IP address directly in so many places, but since it's an elastic IP, it's not so bad.

One alternative is to look up the hbase master by tag and get it's IP address that way:
`aws ec2 describe-instances --filters "Name=tag:Name,Values=telemetry-hbase" | jq -r '.Reservations[0].Instances[0].NetworkInterfaces[0].PrivateIpAddress'`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/78#-:-KZgKwDojuTv4mhHrdY3:b-ss7fzc)*

**Comment by vitillo** [comment]
Done, RFAL.

**Comment by mreid-moz** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mozilla/telemetry-airflow/78#-:-K_9i1cRVBkb6JYrA7ix:bnfp4nl)*

**Pull request merged**
