### PR TITLE
Use default EMR release for telemetry_aggregates

### PR DESCRIPTION
**Pull request by vitillo**
Note: this PR depends on #90 & mozilla/python_mozaggregator#42.

https://bugzilla.mozilla.org/show_bug.cgi?id=1344020.

### CODE REVIEW

**Comment by mreid-moz** [comment]
Please rebase this PR against master

**Comment by vitillo** [comment]
@mreid-moz done

**Comment by vitillo** [comment]
Please don't merge until the PR for mozaggregator lands.

**Comment by mreid-moz** [comment]
ACK

**Pull request merged**
